#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define IDM_EXIT                                105
#define IDI_CLEARVIEW                           107
#define IDI_SMALL                               108
#define IDC_CLEARVIEW                           109
#define IDD_ADD_APP                             116
#define IDD_SETTINGS                            117
#define IDD_SETUP                               118
#define IDD_ADD_WINDOW                          120
#define IDB_DINO                                122
#define IDC_LIST_ADD_APPS                       40000
#define IDC_LIST_ADD_WINDOWS                    40000
#define IDM_OPEN                                40000
#define IDS_APP_TITLE                           40000
#define IDAPPLY                                 40001
#define IDC_CHECKBOX_AUTO_STARTUP               40001
#define IDM_PAUSE                               40001
#define IDC_CHECKBOX_FORCE                      40002
#define IDC_STATIC_RUNNING_APPS                 40002
#define IDM_SETTINGS                            40002
#define IDC_CHECKBOX_FOREGOUND_ONLY             40003
#define IDC_LISTAPPS                            40003
#define IDC_STATIC_CLASS_NAME                   40003
#define IDC_BUTTON_BROWSE                       40004
#define IDC_EDIT_CLASS_NAME                     40004
#define IDC_STATIC_BACKGROUND                   40004
#define IDC_BUTTON_APP_ADD                      40005
#define IDC_BUTTON_WINDOW_ADD                   40006
#define IDC_BUTTON_APP_REMOVE                   40007
#define IDC_BUTTON_WINDOW_REMOVE                40008
#define IDC_LIST_WINDOWS                        40009
#define IDC_STATIC_FOREGROUND                   40010
#define IDC_CHECKBOX_ENABLE_TRANSPARENCY        40011
#define IDC_SLIDER_FOREGROUND                   40012
#define IDC_STATIC_WINDOWS                      40013
#define IDC_STATIC_APPS                         40014
#define IDC_STATIC_TRANSPARENCY                 40015
#define IDC_SLIDER_BACKGROUND                   40016
